#!/usr/bin/env python3
"""Generate a v2 combined-briefing page from a validated data file.

usage: python3 tools/gen_briefing.py DATA.json [--site SITE_ROOT] [--out OUT.html] [--no-patch-prev]

- Validates first (tools/validate_briefing.py); aborts with exit 1 on any error.
- Writes SITE_ROOT/YYYY/YYYY-MM-DD.html (default SITE_ROOT = this repo), using /assets/briefing.css.
- Links the same-date AI daily (/ai/YYYY-MM-DD.html) when it exists in SITE_ROOT, else /ai/.
- Fills the previous v2 page's empty "下一期" slot (only pages generated by this tool; legacy pages untouched).
- The SEO/og block is added afterwards by rebuild_index.py → build_site_meta.py.
"""
from __future__ import annotations

import html
import math
import re
import sys
from datetime import date
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))
from briefing_common import (  # noqa: E402
    HEAD_ICONS, SECTIONS, SITE, bar_html, css_href, date_cn, reading_minutes, tag_html,
)
import validate_briefing as V  # noqa: E402

E = html.escape
GEN_MARK = '<meta name="generator" content="briefing-v2">'


def srcs(ss):
    return " · ".join(f'<a href="{E(s["url"])}">{E(s["name"])}</a>' for s in ss)


def neighbours(site: Path, d: str):
    pages = sorted(p for p in site.glob("[0-9][0-9][0-9][0-9]/*.html") if re.fullmatch(r"\d{4}-\d{2}-\d{2}", p.stem))
    prev = [p for p in pages if p.stem < d]
    nxt = [p for p in pages if p.stem > d]
    f = lambda p: (f"{int(p.stem[5:7])}月{int(p.stem[8:10])}日", f"/{p.parent.name}/{p.name}")  # noqa: E731
    return (f(prev[-1]) if prev else None), (f(nxt[0]) if nxt else None), (prev[-1] if prev else None)


def render(data: dict, site: Path) -> str:
    d = data["date"]
    dd = date.fromisoformat(d)
    ai_page = site / "ai" / f"{d}.html"
    ai_href = f"/ai/{d}.html" if ai_page.exists() else "/ai/"
    if not ai_page.exists():
        print(f"WARN  AI daily {ai_page} not found; AI links point to /ai/ (re-run after it is published)")

    label = {}
    for k, name, _ in SECTIONS:
        sec = data["sections"][k]
        for n, st in enumerate(sec.get("stories") or [], 1):
            label[st["id"]] = f"{name}·{n}"
        for b in sec.get("briefs") or []:
            label[b["id"]] = f"{name}·简讯"

    reading, chips, rail, rows, secs = [data["summary"]], [], [], [], []
    n_story = n_brief = 0
    for k, name, full in SECTIONS:
        sec = data["sections"][k]
        stories, briefs = sec.get("stories") or [], sec.get("briefs") or []
        n_story += len(stories)
        n_brief += len(briefs)
        parts, stext = [], []
        if k == "ai":
            parts.append(f'<p class="secnote">本栏只摘 2–3 条，完整版见 <a href="{ai_href}">'
                         f'{"今日 AI 日报" if ai_href != "/ai/" else "AI 日报"}</a>。</p>')
        if not stories and not briefs:
            parts.append(f'<p class="empty">{E(sec.get("empty") or "今日从缺。")}</p>')
        for n, st in enumerate(stories, 1):
            ctx = ""
            if st.get("prev"):
                ctx += f'<div class="ctx prev"><span class="lbl">前情</span><p>{E(st["prev"])}</p></div>'
            an = '<span class="tag t-an">分析</span>' if st.get("why_analysis") else ""
            ctx += f'<div class="ctx"><span class="lbl">为什么重要</span>{an}<p>{E(st["why"])}</p></div>'
            if st.get("watch"):
                ctx += f'<div class="ctx next"><span class="lbl">看点</span><p>{E(st["watch"])}</p></div>'
            detail = f'<p>{E(st["detail"])}</p>' if st.get("detail") else ""
            more = ""
            if k == "ai" and st.get("ai_anchor") and ai_page.exists():
                more = f'<p class="from-ai"><a href="/ai/{d}.html#{E(st["ai_anchor"])}">AI 日报全文 →</a></p>'
            parts.append(f'''
      <article class="story" id="{st["id"]}">
        <div class="kicker"><span class="num">{name} · {n}</span>{tag_html(st["tags"])}<span class="org">{E(st["org"])}</span></div>
        <h3>{E(st["title"])}</h3>
        <p class="dek">{E(st["lede"])}</p>
        {detail}
        {ctx}
        <p class="sources"><span>来源</span>{srcs(st["sources"])}</p>{more}
      </article>''')
            stext += V.story_text(st)
            rail.append((k, full, st["id"], st["title"]))
            rows.append(f'<tr><td class="sec"><a href="#{st["id"]}">{name}</a></td>'
                        f'<td class="ttl"><a href="#{st["id"]}">{E(st["title"])}</a></td></tr>')
        if briefs:
            lis = "".join(f'<li id="{b["id"]}"><b>{E(b["title"])}</b> {E(b["text"])} '
                          f'<span class="bsrc">{tag_html(b["tags"])} {srcs(b["sources"])}</span></li>' for b in briefs)
            parts.append(f'<div class="briefs"><h4>简讯</h4><ul>{lis}</ul></div>')
            stext += [b["title"] + b["text"] for b in briefs]
        if sec.get("skipped"):
            parts.append(f'<p class="skipped">编辑略过：{E(sec["skipped"])}</p>')
        mins = max(1, round(reading_minutes(" ".join(stext))))
        reading += stext
        meta = f'{len(stories)} 条要闻' + (f' · {len(briefs)} 条简讯' if briefs else '') + f' · 约 {mins} 分钟'
        secs.append(f'''
    <section id="s-{k}" class="sec sec-{k}">
      <header class="sechead"><h2>{full}</h2><span class="secmeta">{meta}</span></header>
      {"".join(parts)}
    </section>''')
        chips.append(f'<a href="#s-{k}" class="chip c-{k}">{name}<span>{len(stories) + len(briefs)}</span></a>')

    top = []
    for t in data["top3"]:
        links = "、".join(f'<a href="#{r}">{label[r]}</a>' for r in t["refs"])
        top.append(f'<li><p><b>{E(t["lead"])}</b>{E(t["fact"])}</p><p class="an"><span class="tag t-an">分析</span>'
                   f'{E(t["analysis"])} <span class="jump">见 {links}</span></p></li>')
        reading += [t["lead"], t["fact"], t["analysis"]]
    total_min = max(1, math.ceil(reading_minutes(" ".join(reading))))

    rail_html, cur = "", None
    for k, full, iid, title in rail:
        if k != cur:
            rail_html += ("</ol>" if cur else "") + f'<p class="rail-sec r-{k}"><a href="#s-{k}">{full}</a></p><ol>'
            cur = k
        rail_html += f'<li><a href="#{iid}">{E(title)}</a></li>'
    rail_html += "</ol>" if cur else ""

    corr = "".join(f'<aside class="corr"><b>更正</b>{E(c["text"])}（<a href="{E(c["source"]["url"])}">'
                   f'{E(c["source"]["name"])}</a>）</aside>' for c in data.get("corrections") or [])
    notes = f'<p class="notes"><b>本期说明</b>{E(data["notes"])}</p>' if data.get("notes") else ""

    prev, nxt, _ = neighbours(site, d)
    if "prev" in data:
        prev = (data["prev"]["label"], data["prev"]["href"]) if data["prev"] else None
    if "next" in data:
        nxt = (data["next"]["label"], data["next"]["href"]) if data["next"] else None
    prev_a = f'<a class="pn-prev" href="{E(prev[1])}">← 上一期 {E(prev[0])}</a>' if prev else '<a class="pn-prev"></a>'
    next_a = f'<a class="pn-next" href="{E(nxt[1])}">下一期 {E(nxt[0])} →</a>' if nxt else '<a class="pn-next"></a>'
    legend = "".join(f"<li>{x}</li>" for x in [
        f'{tag_html(["off"])} 公司公告、政府文件、获奖公告等一手材料；{tag_html(["cross"])} 多个独立信源分别证实',
        f'{tag_html(["peer"])} 已发表的同行评审论文；{tag_html(["pre"])} 未经同行评审',
        f'{tag_html(["media"])} 媒体报道，已读原文；{tag_html(["paywall"])} 原文付费，只读到转述；{tag_html(["single"])} 只有一个来源',
        f'{tag_html(["rumor"])} 未经证实的传闻或媒体推断',
        f'{tag_html(["mouse"])}{tag_html(["cell"])}{tag_html(["human"])}{tag_html(["rct"])} 研究对象与设计（抗衰栏必标）',
        f'{tag_html(["an"])} 编辑判断，不是事实'])
    title = f"每日简报 · {dd.year}年{dd.month}月{dd.day}日"
    links = [("AI 日报", ai_href, False), ("订阅", "/feed.xml", False)]  # 「每日简报」brand → / covers 往期
    return f'''<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  {GEN_MARK}
  <meta name="color-scheme" content="light dark">
  {HEAD_ICONS}
  <link rel="stylesheet" href="{css_href(site)}">
</head>
<body class="briefing">
{bar_html("".join(chips), links, brand=True)}
<div class="page">
  <aside class="rail" aria-label="本期目录"><p class="rail-h">本期目录</p>{rail_html}</aside>
  <main>
    <header class="mast">
      <h1><a class="home" href="/">每日简报</a></h1>
      <p class="meta"><time datetime="{d}">{date_cn(dd)}</time><span>阅读约 {total_min} 分钟</span><span>{n_story} 条要闻 · {n_brief} 条简讯</span></p>
      <p class="lede">{E(data["summary"])}</p>
    </header>
    <section class="top3" aria-label="今日三件事">
      <h2>今日三件事</h2>
      <ol>{"".join(top)}</ol>
    </section>
    <details class="digest-box">
      <summary>全部要闻速览</summary>
      <table class="digest"><thead><tr><th class="sec">栏目</th><th class="ttl">条目</th></tr></thead><tbody>{"".join(rows)}</tbody></table>
    </details>
    {"".join(secs)}
    {corr}
    <footer>
      {notes}
      <details><summary>证据标签怎么读</summary><ul class="legend">{legend}</ul></details>
      <p class="pn">{prev_a}<a href="/">全部往期</a>{next_a}</p>
      <p class="disc">来源为公开报道、期刊与预印本。仅供阅读参考，不构成投资或医疗建议。</p>
    </footer>
  </main>
</div>
</body>
</html>
'''


def link_ai_page(site: Path, d: str) -> None:
    """The AI daily usually publishes first and then links to the newest combined page; repoint its
    「当日简报」/「最新综合简报」links at today's page. Only v2 AI pages are touched."""
    ai = site / "ai" / f"{d}.html"
    if not ai.exists():
        return
    raw = ai.read_text(encoding="utf-8")
    if 'content="ai-daily-v2"' not in raw:
        return
    href = f"/{d[:4]}/{d}.html"
    new = re.sub(r'<a href="(?!/")[^"]*">(?:当日简报|最新简报)</a>', f'<a href="{href}">当日简报</a>', raw, count=1)
    new = re.sub(r'<a href="(?!/")[^"]*">每日简报</a>', f'<a href="{href}">当日简报</a>', new, count=1)  # pre-nav v2 AI pages
    new = re.sub(r'<a href="[^"]*">最新综合简报</a>', f'<a href="{href}">当日综合简报</a>', new)
    if new != raw:
        ai.write_text(new, encoding="utf-8")
        print(f"linked 当日综合简报 in {ai} (commit it too)")


def patch_prev(site: Path, d: str) -> None:
    _, _, prev_path = neighbours(site, d)
    if not prev_path:
        return
    raw = prev_path.read_text(encoding="utf-8")
    if GEN_MARK not in raw or '<a class="pn-next"></a>' not in raw:
        return  # legacy page or already linked: leave untouched
    lab = f"{int(d[5:7])}月{int(d[8:10])}日"
    raw = raw.replace('<a class="pn-next"></a>', f'<a class="pn-next" href="/{d[:4]}/{d}.html">下一期 {lab} →</a>', 1)
    prev_path.write_text(raw, encoding="utf-8")
    print(f"linked 下一期 in {prev_path}")


def main(argv: list[str]) -> int:
    if not argv or argv[0] in ("-h", "--help"):
        print(__doc__)
        return 2
    path = Path(argv[0])
    site = Path(argv[argv.index("--site") + 1]) if "--site" in argv else SITE
    data = V.load(path)
    errs, warns = V.validate(data, path)
    for w in warns:
        print(f"WARN  {w}")
    if errs:
        for e in errs:
            print(f"ERROR {e}", file=sys.stderr)
        print(f"FAIL: {len(errs)} validation error(s); nothing written.", file=sys.stderr)
        return 1
    d = data["date"]
    out = Path(argv[argv.index("--out") + 1]) if "--out" in argv else site / d[:4] / f"{d}.html"
    html_out = render(data, site)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html_out, encoding="utf-8")
    post = []
    V.check_html(out, post)
    if post:
        for e in post:
            print(f"ERROR {e}", file=sys.stderr)
        out.unlink()
        print("FAIL: rendered page failed checks; removed.", file=sys.stderr)
        return 1
    print(f"wrote {out} ({len(html_out)} bytes)")
    if "--no-patch-prev" not in argv:
        patch_prev(site, d)
    link_ai_page(site, d)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
